name: Build Windows XMRig

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSYS2 and Dependencies
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-libuv
          mingw-w64-x86_64-openssl
          mingw-w64-x86_64-hwloc

    - name: Compile XMRig (Static)
      shell: msys2 {0}
      run: |
        cmake -B build -G "Ninja" -DBUILD_STATIC=ON
        cmake --build build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: xmrig-no-donate-win64
        path: build/xmrig.exe
